Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 17
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
