Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 17
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
